---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://blog.chixq.com

posts:
  permalink: /:year-:month-:day/:title/
  summary_lines: 20
  latest: 5 
  exclude: '~$'

pages:
  permalink: 'pretty'
